### ISSUE TITLE
Unrewarding cheese success

### ISSUE THREAD

**Issue by mkeedlinger** [janka102/cheesy-ant#1]
When the ant finally gets to the cheese (this can take some time on a large screen!), nothing happens!

Needs to better celebrate my success. It's the only success I've had for a while.

**Comment by janka102** [comment]
Ah yes this is true, it is most unsatisfying! I will try to add something when the ant reaches the cheese.

Now I just need to figure out how to check if a point is inside a triangle...

**Comment by janka102** [comment]
@mkeedlinger I have just pushed some changes that shows you a message when you reach the cheese. Check it out and let me know if it is satisfying enough :cheese: :ant:

**Comment by mkeedlinger** [comment]
It's acceptable.
